steps:
  - name: sonarsource/sonar-scanner-cli
    args:
    - '-Dsonar.host.url=https://sonarcloud.io'
    - '-Dsonar.projectKey=thinkdigitalgroupprojectagora_${REPO_NAME}'
    - '-Dsonar.organization=thinkdigitalgroupprojectagora'
    - '-Dsonar.sources=.'
    - '-Dsonar.projectVersion=${COMMIT_SHA}'
    - '-Dsonar.pullrequest.key=${_PR_NUMBER}'
    secretEnv: ['SONAR_TOKEN']

availableSecrets:
  secretManager:
  - versionName: projects/47821157048/secrets/SONAR_TOKEN/versions/latest
    env: 'SONAR_TOKEN'