steps:
  - name: 'eu.gcr.io/$PROJECT_ID/sonarcloud/sonar-scanner-cli'
    args:
    - '-Dsonar.host.url=https://sonarcloud.io'
    - '-Dsonar.projectKey=thinkdigitalgroupprojectagora_case-study-sonarcloud-poc'
    - '-Dsonar.organization=thinkdigitalgroupprojectagora'
    - '-Dsonar.sources=.'
    secretEnv: ['SONAR_TOKEN']

availableSecrets:
  secretManager:
  - versionName: projects/47821157048/secrets/SONAR_TOKEN/versions/latest
    env: 'SONAR_TOKEN'